# Generated by Django 5.2.5 on 2025-09-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_event_participent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
